### PR TITLE
add new svg icons

### PR DESCRIPTION
**Pull request by pvalles-simtlix**
Add icons in SVG format. 

Avax, Joe, Klo, Usdt, Usdc, Qi, Png, Xava, Link

### CODE REVIEW

**Comment by antonfrolovsky** [comment]
I think all icons should be optimize through [svgo](https://github.com/svg/svgo)

**Comment by ricburton** [comment]
Can we help with this?

**Comment by tommdn** [comment]
Hello @pvalles-simtlix.
`USDT`, `USDC`, `LINK` are already available.
`AVAX` will join them in the next batch (it is ready along with a lot of others of the requested ones in the issues, but I did not have time to make the release recently — I hope I can release this weekend).
Please make an issue for the others if you need them so I can make them in the different sizes/colors that are needed: we cannot add only SVGs.

@antonfrolovsky We run `svgo` automatically when a release is made (multipass mode).

@ricburton Yes by adding the relevant information in the corresponding issues (color/svg files) I can add them in the upcoming batch.

**Comment by ricburton** [comment]
We need to fix the ETH one. So I should prepare files?

**Comment by tommdn** [comment]
@ricburton Regarding the `ETH` icon I've answered in the issue you've made, is the compromise I mentioned acceptable for you? If yes I will update it.

**Pull request closed without merging**
