### PR TITLE
Updating SOL icon with official branding guidelines https://solana.com/branding

### PR DESCRIPTION
**Pull request by FabioAmelia**
Updating SOL icon with official branding guidelines https://solana.com/branding

Screenshot 2021-11-02 at 13 46 24

### CODE REVIEW

**Comment by tommdn** [comment]
@FabioAmelia hello. Please take a look at the icons in this repository. The aim is to get consistency between different brands — in particular we do not use gradients (whatever the official branding guidelines are). If you take a look at the Solana branding guidelines page you did share they propose solid icons as well (which we do use).

**Comment by FabioAmelia** [comment]
Understood, I was proposing it because I saw that also AEUR has a gradient logo.
So, what if we update it with a black background like the official guideline, instead of the current green?

Like this:
Screenshot 2021-11-02 at 15 36 03

**Comment by tommdn** [comment]
Indeed the color we have chosen `#66f9a1` does not reflect the Solana brand accurately (it is more like their secondary color when we look at their gradient). I think we should go with the official purple color `#9945ff`, which is on the branding page.
If a distinctive color exists it is better than going with a solid black or white, unless black or white is the branding main color. Here, they are giving black and white versions for those who want to do neutral interfaces. We do provide a neutral icon in the `black` section.
This will be fixed shortly.

**Comment by tommdn** [comment]
Indeed the color we have chosen `#66f9a1` does not reflect the Solana brand accurately (it is more like their secondary color when we look at their gradient). I think we should go with the official purple color `#9945ff`, which is on the branding page.
If a distinctive color exists it is better than going with a solid black or white, unless black or white is the branding main color. Here, they are giving black and white versions for those who want to do neutral interfaces. We do provide a neutral icon in the `black` section.

**Comment by tommdn** [comment]
Regarding `AEUR` those are different opacities of white. This is allowed but there is only one base color. For example we do that with `ETH` as well.

**Comment by FabioAmelia** [comment]
Screenshot 2021-11-04 at 08 37 58
What about this, so?

**Comment by tommdn** [comment]
@FabioAmelia look at the icons in the repository please, you inverted the colors.

**Comment by tommdn** [comment]
This one has been designed and will be added in the next batch.

**Pull request closed without merging**
