### PR TITLE
Add viewBox to all SVGs

### PR DESCRIPTION
**Pull request by jack-fin**
Hello,

This is an attempt to get viewBox added to the legacy SVG icons which did not have them (such as color/btc.svg).

Followup to https://github.com/spothq/cryptocurrency-icons/pull/275

Without modifying any attribute order. It was done using the tool suggested in the above PR (https://github.com/guylando/svgo-addViewBox/blob/master/addViewBox.js)

### CODE REVIEW

**Comment by jack-fin** [comment]
I have a follow-up to this that I'd like to ask.

I am looking to hopefully use the `white` icons and override their path fill color. I have this working using the following library: https://github.com/kristerkari/react-native-svg-transformer

However, for this to work I have to also remove the following prop from the "white" SVGs: `fill-rule="evenodd"`

By doing this, I am able to change the WHITE BTC Svg to look coral as seen here: 
Screen Shot 2020-10-24 at 10 11 21 PM

I am not super well versed in SVG so do not know the implications of having this fill-rule vs not having it.

**Comment by tommdn** [comment]
@jack-fin hello. Removing `evenodd` reverts the SVG fill rule to the default `nonzero`. This can lead to a misconception of what is inside or outside the shape during drawing. `evenodd` always alternates between inside and outside, whereas `nonzero` (as it name stands) will fill if the paths intersection winding order is non-zero.

The majority of the icons were made using Sketch set operations, and I do not know whether or not it alternates between clockwise/counter-clockwise paths. If yes, it would mean the fill mode can either be `evenodd` or `nonzero` without altering the render, and we could proceed.

Why did you need to remove `evenodd`? What happens when you try to draw with `viewBox` and `evenodd` mode? Is the issue `react-native-svg` is not compatible with `evenodd`? If yes I think we should check with the corresponding development team why it is the case, as `fill-rule` is not something exotic but exists in the W3C recommendations (see https://www.w3.org/TR/SVG11/painting.html from 2011).

Thank you for your efforts — waiting for your input on this.

**Comment by jack-fin** [comment]
@tommdn Thanks for the explanation of `evenodd` that makes sense!

I can look into why the color override was not working for me in react-native, its very possible its a user error on my end. I think outside of that though, I was hoping to merge this PR to add the viewBox to the older .svg files. 

Thank you!

**Comment by tommdn** [comment]
@jack-fin You're welcome. Please keep me informed.
Of course regarding adding `viewBox` to older icons. I'll take a look at it.

**Comment by jack-fin** [comment]
Appreciate it, I believe that is all this PR should do,

**Comment by swapnilsarwe** [comment]
@tommdn - even I have been using this icons and saw viewBox missing in several icons. Let me know if there is anything I can help you with.

**Comment by tommdn** [comment]
@jack-fin Hello. This should now be present on all icons. Please let me know if there are any issues.

**Pull request closed without merging**
